export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { About } from "./About";
export { Skills } from "./Skills";
export { Projects } from "./Projects";
export { Contact } from "./Contact";
export { Journey } from "./Journey";
export { TechWeb } from "./TechWeb";
export { TechChip } from "./TechChip";
